name: Generate Snake Animation

on:
  # Ejecuta el workflow automáticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite la ejecución manual desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Paso 1: Clona el repositorio
      - uses: actions/checkout@v3

      # Paso 2: Genera la animación de la serpiente
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ochv-dev
          outputs: |
            # Versión Light: Azul estándar de GitHub
            dist/github-snake.svg?color_snake=#0969da&color_dots=#ebedf0,#b6e3ff,#80cfff,#4db8ff,#0969da
            # Versión Dark: Azul neón (modo oscuro)
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#161b22,#0d1117,#1f6feb,#388bfd,#58a6ff

      # Paso 3: Sube los archivos generados (dist) a la rama 'output'
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
