name: Generate Snake Animation

on:
  # Ejecuta el workflow automáticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite la ejecución manual desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Paso 1: Clona el repositorio
      - uses: actions/checkout@v3

      # Paso 2: Genera la animación de la serpiente
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ochv-dev
          outputs: |
            # Modo Claro: Serpiente Azul (#0969da) + Puntos Verdes (por defecto)
            dist/github-snake.svg?color_snake=#0969da
            # Modo Oscuro: Serpiente Azul Neón (#58a6ff) + Puntos Verdes Neón (palette=github-dark)
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#58a6ff

      # Paso 3: Sube los archivos generados (dist) a la rama 'output'
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
